apiVersion: apps/v1
kind: Deployment
metadata:
  name: journaldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journaldb
  template:
    metadata:
      labels:
        app: journaldb
    spec:
      containers:
        - name: journaldb
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: journaldb-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: journaldb-secret
                  key: MYSQL_DATABASE
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: journaldb-secret
                  key: DATABASE_HOST

---
apiVersion: v1
kind: Service
metadata:
  name: journaldb-service
spec:
  selector:
    app: journaldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
